# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
cask "ob" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "069d747eeac4000918a908c033dd956fd565a030a4942b1ab364ccf032ad15ed"
      url "https://github.com/openbindings/ob/releases/download/v#{version}/ob_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad83f835f66ecee16ba193e6cdb704b82ad73971bb91fe4586bc459da6666ec9"
      url "https://github.com/openbindings/ob/releases/download/v#{version}/ob_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f78cd5b5420603770f4505cf77a37d57c4491964a08ff4034642d01eba7fb313"
      url "https://github.com/openbindings/ob/releases/download/v#{version}/ob_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7d441be6a5d527acd084dfd761eb82cad8160ad4d71d3d265c3b497afd641a1"
      url "https://github.com/openbindings/ob/releases/download/v#{version}/ob_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ob"
  desc "The OpenBindings CLI"
  homepage "https://openbindings.com"

  binary "ob"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ob"]
  end
end
