# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ob < Formula
  desc "The OpenBindings CLI"
  homepage "https://openbindings.com"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_darwin_amd64.tar.gz"
      sha256 "0cadeff93e559579d40a11827849b98a4325d83f2e0d091c0d047c71234b972e"

      def install
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_darwin_arm64.tar.gz"
      sha256 "da54ac6cb4f54da7450731fd62409b2a7dbd8d8a2134fbe8de7a2099519cad63"

      def install
        bin.install "ob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_linux_amd64.tar.gz"
      sha256 "c3b0272857aef774ec86a2f65764f503288a113ed603cb7de9ffbd8e4d05119d"
      def install
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_linux_arm64.tar.gz"
      sha256 "aad0a61fdc6e7ed99d8c982209a2e5405b87da601a1f42a282c2bc7f51c4826d"
      def install
        bin.install "ob"
      end
    end
  end

  test do
    system "#{bin}/ob", "version"
  end
end
