# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ob < Formula
  desc "The OpenBindings CLI"
  homepage "https://openbindings.com"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_darwin_amd64.tar.gz"
      sha256 "069d747eeac4000918a908c033dd956fd565a030a4942b1ab364ccf032ad15ed"

      def install
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_darwin_arm64.tar.gz"
      sha256 "ad83f835f66ecee16ba193e6cdb704b82ad73971bb91fe4586bc459da6666ec9"

      def install
        bin.install "ob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_linux_amd64.tar.gz"
      sha256 "f78cd5b5420603770f4505cf77a37d57c4491964a08ff4034642d01eba7fb313"
      def install
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openbindings/ob/releases/download/v0.1.0/ob_0.1.0_linux_arm64.tar.gz"
      sha256 "c7d441be6a5d527acd084dfd761eb82cad8160ad4d71d3d265c3b497afd641a1"
      def install
        bin.install "ob"
      end
    end
  end

  test do
    system "#{bin}/ob", "version"
  end
end
